In [1]:
import numpy as np

In [6]:
brb=np.array([1,2,3])

In [18]:
import pandas as pd

In [19]:
bidu=pd.array([[5,6,7],[8,9,7]])

In [20]:
print (pd)

<module 'pandas' from 'C:\\Users\\Bharat Sakarwal\\anaconda3\\lib\\site-packages\\pandas\\__init__.py'>


In [21]:
print(bidu)

<PandasArray>
[[5, 6, 7], [8, 9, 7]]
Length: 2, dtype: object


In [22]:
bidu[1][1]=1

In [19]:
bidu

<PandasArray>
[[5, 1, 7], [8, 9, 7]]
Length: 2, dtype: object

In [20]:
bidu.shape

(2,)

In [21]:
print(bidu.shape)

(2,)


In [22]:
bidu[1][1]

9

In [23]:
arr2=np.array([[23,31,45,87],[10,12,13,14]])

In [24]:
arr2.shape

(2, 4)

In [31]:
arrs=np.array(['India','Love','Me'])

In [32]:
arrs

array(['India', 'Love', 'Me'], dtype='<U5')

In [45]:
arrR = pd.linspace(0,20, 2)

AttributeError: module 'pandas' has no attribute 'linspace'

In [46]:
arrR = pd.linspace(0,20,2)

AttributeError: module 'pandas' has no attribute 'linspace'

In [47]:
arrR = pd.LinSpace(0,20,2)

AttributeError: module 'pandas' has no attribute 'LinSpace'

In [53]:
arrR = np.linspace(0,20, 6)
arrR

array([ 0.,  4.,  8., 12., 16., 20.])

In [42]:
arrP = np.arange(0,20,2)

In [49]:
arr= np.random.rand(6)
arr

array([0.16208139, 0.26657261, 0.80201687, 0.07459026, 0.8340842 ,
       0.77639155])

In [57]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [60]:
arr=[1,2,3]
print (np.repeat(arr,2))

[1 1 2 2 3 3]


In [61]:
print (np.tile(arr,3))

[1 2 3 1 2 3 1 2 3]


In [45]:
a=np.diag([1,2,3])
np.diag(a)
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [64]:
arr=print(np.random.rand(5,5))

[[0.21074132 0.08345264 0.97038807 0.71971412 0.89694933]
 [0.16633559 0.33902993 0.15974291 0.80555387 0.96193279]
 [0.41323246 0.24027277 0.48795972 0.9388184  0.73848192]
 [0.72146943 0.94137547 0.59476616 0.32433954 0.50955682]
 [0.31355744 0.08299036 0.21855657 0.61093155 0.35560648]]


In [68]:
np.diag(arr)


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [71]:
np.ndim(arr)

1

In [73]:
np.size(arr)

3

In [84]:
art=np.random.rand(2,3)
art

array([[0.68535982, 0.95339335, 0.00394827],
       [0.51219226, 0.81262096, 0.61252607]])

In [85]:
art+10

array([[10.68535982, 10.95339335, 10.00394827],
       [10.51219226, 10.81262096, 10.61252607]])

In [94]:
arr
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [97]:
np.tan(arr)

array([ 1.55740772, -2.18503986, -0.14254654])

In [108]:
arr

[1, 2, 3]

In [113]:
np.sum(arr2,axis=1)

array([186,  49])

In [114]:
arr2

array([[23, 31, 45, 87],
       [10, 12, 13, 14]])

In [119]:
np.max(arr2,axis=1)

array([87, 14])

In [137]:
np.max(arr2,axis=0)

array([23, 31, 45, 87])

In [128]:
np.mean(arr2)

29.375

In [127]:
np.std(arr2)

24.46904932767107

In [126]:
np.var(arr2)

598.734375

In [138]:
arr2[0:,1:3]

array([[31, 45],
       [12, 13]])

In [140]:
np.sort(arr2)

array([[23, 31, 45, 87],
       [10, 12, 13, 14]])

In [141]:
arr2.T

array([[23, 10],
       [31, 12],
       [45, 13],
       [87, 14]])

In [96]:
arr3=np.append(arr2,0)
arr3

NameError: name 'arr2' is not defined

In [12]:
import numpy as np
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr3=np.insert(arr2,1,[88])
arr3

array([ 1, 88,  2,  3,  4,  5,  6,  7,  8,  9])

In [21]:
arrC=np.copy(arr3)
arrC
arrP=np.delete(arrC,1)
arrP,arrC

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 1, 88,  2,  3,  4,  5,  6,  7,  8,  9]))

In [33]:
a = np.array([[1,2,8,99], [3,4,9,88]])
b = np.array([[5,6,10,77],[43,57,84,61]])
np.concatenate((a, b), axis=1)

array([[ 1,  2,  8, 99,  5,  6, 10, 77],
       [ 3,  4,  9, 88, 43, 57, 84, 61]])

In [47]:
a = np.array([[1,2,8,99], [3,4,9,88]])
b = np.array([[5,6,10,77],[43,57,84,61]])
np.concatenate((a, b), axis=0)

array([[ 1,  2,  8, 99],
       [ 3,  4,  9, 88],
       [ 5,  6, 10, 77],
       [43, 57, 84, 61]])

In [49]:
u,c=np.unique(a,return_counts=True)
print(u)
print(c)

[ 1  2  3  4  8  9 88 99]
[1 1 1 1 1 1 1 1]


In [62]:
e = np.array([[1,2,8,99], [3,4,9,88]])
f = np.array([[5,2,8,77],[43,1,84,61]])
print(np.intersect1d(e,f))
print(np.union1d(e,f))
#print(np.unique(e))
print(np.setdiff1d(e,f)) #whats in array e but not in array f
print(np.setxor1d(e,f)) #whats in array e but not in array f & whats in array f but not in array e

[1 2 8]
[ 1  2  3  4  5  8  9 43 61 77 84 88 99]
[ 3  4  9 88 99]
[ 3  4  5  9 43 61 77 84 88 99]


In [65]:
#"""Hi How are you"""

In [2]:
#i=np.array([1,2,3,4,5])
for r in range(10):
    print(r)

0
1
2
3
4
5
6
7
8
9


In [136]:
a=13;b=20
#print(a,b)
print("a is {} and b is {}".format(a,b))
print(a+b)
print(float(a/b))
print(b%a) # return remainder

a is 13 and b is 20
33
0.65
7


In [88]:
index1=20;index2=70

print("Numbers between{} and {}".format(index1,index2))

for num in range(index1,index2+1):
    if num>1:
        isdivisible=False;
        for i in range(2,num):
            if num % i == 0:
                isdivisible=True;
                break
        if not isdivisible:
            print(num);
            

Numbers between20 and 70
23
29
31
37
41
43
47
53
59
61
67


In [87]:
number=int(input("Enter a Number"))
isdivisible=False
for i in range (2,number):
        if number%i==0:
            isdivisible=True
            print("{} is divisible by{}".format(number,i))
          #  break
if not isdivisible:
    print("Prime Number{}".format(number))
else:
    print("{} is not a Prime Number".format(number))

Enter a Number16
16 is divisible by2
16 is divisible by4
16 is divisible by8
16 is not a Prime Number


In [1]:
num=int(input("e"))
#num=-4

if num>0:
    print("Postivie No.{}".format(num))
else:
    print("Negative No.")

e6
Postivie No.6


In [5]:
numbers={1,2,3,4,5,6,7,8}

for num in numbers:
    if num%2==0:
        continue
    print(num)

1
3
5
7


In [95]:
numbers=[1,2,3,4,5,6,7,8]
numbers.insert(1,9)
print("{}".format(numbers))
numbers.append(10)
numbers.remove(1)
print("{}".format(numbers))
p=numbers.pop(2)
p

[1, 9, 2, 3, 4, 5, 6, 7, 8]
[9, 2, 3, 4, 5, 6, 7, 8, 10]


3

In [4]:
number=[1,2,3,4,5,6,7,8]
number.remove(1)
number
number.reverse()
number

[8, 7, 6, 5, 4, 3, 2]

In [11]:
squ=[]
for i in range(10):
    squ.append(i**2)
print(squ)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [1]:
n=[-10,-20,30,40]
for i in n:
    if i>0:
        print(i)

30
40


In [9]:
my_dict={1:'Hello',2:"World"}
my_dict[1]='Why'
my_dict.pop(2)
my_dict

{1: 'Why'}

In [16]:
d={1:'Hello',2:"World"}

for i in d.values():
    print(i)
    
for i in d.items():
    print(i)

Hello
World
(1, 'Hello')
(2, 'World')


In [23]:
d={'a':1,'b':2,'c':3}

for i in d.values():
    if i>=2:
        print(i)

2
3


In [33]:
d={'a':1,'b':2,'c':3}
d1={k:v for k,v in d.items() if v>1}
d1

{'b': 2, 'c': 3}

In [40]:
count=0
for i in "Hello World":
    if i=='l':
        count+=1 
print(count)

3


In [118]:
mystr="HELLO WORLD, I AM AWESOME"
mystr.lower()
mystr.split()
#' '.join(['HELLO', 'WORLD,', 'I', 'AM', 'AWESOME'])

['HELLO', 'WORLD,', 'I', 'AM', 'AWESOME']

In [12]:
"GOOD MORNING".find("MO")

5

In [17]:
s1="BAD MORNING"
s2=s1.replace("BAD","GOOD")
print(s1)
s2

BAD MORNING


'GOOD MORNING'

In [30]:
s="MajdaM"
s1=s.lower()

s2=reversed(s1)

if list(s1)==list(s2):
    print('Palindrome')
else:
    print('No Palindrome')

No Palindrome


In [37]:
mystr="Hello World I am jumbled up"   #sort and print a string
words=mystr.split()
words.sort()
for i in words:
    print(i)

Hello
I
World
am
jumbled
up


In [41]:
def print_name(name):
    """
    Indentation of a function
    """
    print("Hello "+str(name))
    
print_name('Satish')

Hello Satish


In [70]:
def get_HCF(a,b):
    '''
    This is to print HCF of 2 nos
    '''
    hcf=1
    s=a
    if s>b:
        s=b
    
    for i in range (1,s+1):
        if (a%i==0) and (b%i==0):
            hcf =i
    return hcf
    
n1=int(input("enter a number "))
n2=int(input("enter a number "))


print("HCF of {0} and {1} is {2}".format(n1,n2,get_HCF(n1,n2)))
        

enter a number 16
enter a number 4
HCF of 16 and 4 is 4


In [1]:
number=[140,10,20,30,40]

for i,n in enumerate(number):
    print("For Index {0} , value is {1} ".format(i,n))

For Index 0 , value is 140 
For Index 1 , value is 10 
For Index 2 , value is 20 
For Index 3 , value is 30 
For Index 4 , value is 40 


In [13]:
n=5
fact=1
for i in range(1,n+1):
    fact*=i
    
print (fact)



120


In [23]:
import pdb

def seq(n):
    for i in range (n):
        pdb.set_trace()
        print(i)
    return

seq(5)

> c:\users\bharat sakarwal\appdata\local\temp\ipykernel_26428\1935371642.py(6)seq()

ipdb> q


BdbQuit: 

In [28]:
L=range(1000)
%timeit [i**2 for i in L]
L

775 µs ± 15.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [52]:
import numpy as np
a=np.arange(10,80,5)
#%timeit [i**2 for i in a]
a

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [48]:
c=np.diag([1,2,3,4])
c
a=np.array([1,3,4,5,5])
b=np.array([0,3,4,5,6])
print(a*b)
print(a+b)
print(b>a)
np.array_equal(a,b)
np.logical_or(a,b)

[ 0  9 16 25 30]
[ 1  6  8 10 11]
[False False False False  True]


array([ True,  True,  True,  True,  True])

In [32]:
a=np.array([1,4,3,6,7])
b=np.array([0,3,4,5,6])
np.any(a<b) # all the elements needs to be false to return false
np.all(a>b) # all the elements needs to be true to return true

False

In [53]:
a=np.array([[1,4,3,6,7],[2,3,4,5,6]])
#np.mean(a)
np.sum(a,axis=0) # axis 0 represents sum by cols, 1 represents sum by rows

array([ 3,  7,  7, 11, 13])

In [88]:
a=np.tile(np.arange(0,50,10), (2,1))
print(a)
np.ravel(a)

#np.shape(a)
#a.T

[[ 0 10 20 30 40]
 [ 0 10 20 30 40]]


array([ 0, 10, 20, 30, 40,  0, 10, 20, 30, 40])

In [98]:
a=np.array([[1,2,3],[4,5,6]])
a
b=a.ravel()
b.reshape(3,2)
c=b[:,np.newaxis]  # add new dimension to array
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [103]:
a=np.arange(24).reshape(4,3,2)
print(a)

a[1,2,1]

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


11

In [129]:
a=np.array([2,7,4,5,6])
b=np.sort(a)
print(b)
c=np.argsort(a) # returns argument value of array after sorting values
print(c)
a[c]

[2 4 5 6 7]
[0 2 3 4 1]


array([2, 4, 5, 6, 7])

In [137]:
n = int(input())
for i in range(0,n):
    print(i**2)

7
0
1
4
9
16
25
36


In [156]:
def seq_string(p):
    """
    
    """
    return p

import __future__ as fn

n = int(input())
for i in range(1,n+1):
    print(i,end="")  # dont want go to new line

3
123

In [171]:
result=[]
x=1
y=1
z=1
n=2
#result=[[i,j,k] for i in range(x) for j in range(y) for k in range(z) if (i+j+k)<n]
result=[[i,j,k] for i in range(x+1) for j in range(y+1) for k in range(z+1) if(i+j+k)!=n]
result

[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]

In [224]:
#n = int(input())
#arr = map(int, input().split())

lst=[1,6,3,4,5]

"""
for i in lst:
    if i>1:
        print("Hello")
"""
b=max(lst)
b
lst.remove(b)
lst
c=max(lst)
c

5

In [76]:
arr = map(int, input().split())


5


n = int(input())
arr = list(range(1,10,2))
lst=arr
b=max(lst)
print(arr)
lst.remove(b)
c=max(lst)
c
print(tuple(arr))

In [117]:
if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    
    for i in range(n):
        if arr[i]>arr[i+1]:
            print(arr[i+1])
            break


2
2


IndexError: list index out of range

In [145]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()
    print(student_marks[query_name])
    a=student_marks[query_name]
    b=float(sum(a)/len(a))
    print(format(b,'.2f'))

1
Arjun 70 98 63
Arjun
[70.0, 98.0, 63.0]
77.00


In [97]:
arr=[2,3,478,4,5]
c=np.sort(arr)
c

for i in range(0,n):
        if arr[i]>arr[i+1]

array([  2,   3,   4,   5, 478])

In [244]:
#n = int(input())
#arr = map(int, input().split())
arr=[2,3,4,5,5]
a=max(arr)
#count=0
q=arr.count(5)
q
"""
for i in arr:
    if i==a:
        count+=1

for j in range(count):
    arr.remove(a) 
        
print(max(arr))
"""

'\nfor i in arr:\n    if i==a:\n        count+=1\n\nfor j in range(count):\n    arr.remove(a) \n        \nprint(max(arr))\n'

In [301]:
students = [['Harry', 37.21], ['Berry', 37.21], ['Tina', 37.2], ['Akriti', 41], ['Harsh', 39]]

#a=min(students)
students[3][1]
marks=[]

#marks=[students[3][1],students[0][1]]
#marks.append(students[1][1])
#marks

for i in range(5):
    marks.append(students[i][1])
marks.sort()
stu=[]

for j in range(4):
     if marks[1]==students[j][1]:
        stu.append(students[j][0])

stu


['Harry', 'Berry']

In [303]:
marksheet=[]
scoresheet=[]
if __name__ == '__main__':
    for _ in range(int(input())):
        name = input()
        score = float(input())
        marksheet+=[[name,score]]
        scoresheet+=[score]
        
    x=sorted(scoresheet)[1]
    
    for n,s in (sorted(marksheet)):
        if x==s:
            print(n)

2
Harry
34
Barry
45
Barry


In [186]:
lst=[0]
lst.append(10)
lst.insert(0,6)
print(lst)
lst.remove(6)
lst.append(9)
lst.append(1)
lst.sort()
print(lst)
lst.pop()
lst.sort(reverse=True)
print(lst)

[6, 0, 10]
[0, 1, 9, 10]
[9, 1, 0]


In [203]:
if __name__ == '__main__':
    N = int(input())
    lst=[2,3]
    cmd=input().split()    
    for i in range (N):
        if cmd[0]=='insert':
            lst.insert(int(cmd[1]),int(cmd[2]))
            print(lst)
        elif cmd[0]=='remove':
            lst.remove(int(cmd[1]))
            print(lst)
        elif cmd[0]=='print':
            print(lst)
        elif cmd[0]=='append':
            lst.append(int(cmd[1]))
            print(lst)
        elif cmd[0]=='pop':
            lst.pop()
            print(lst)
        elif cmd[0]=='sort':
            lst.sort()
            print(lst)
        elif cmd[0]=='reverse':
            lst.reverse()
            print(lst)

1
insert 1 9
[2, 9, 3]


In [183]:
from functools import reduce
n=[10,20,30,40]
def multiply(x,y):
    print(x,y)
    return (x*y)

p=reduce(multiply,n)
p

10 20
200 30
6000 40


240000

In [212]:
lst=[i for i in range(1,11)]
lst
triple=list(map(lambda x:x*x*x,lst))
triple

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [279]:
lst1=[i for i in range(1,11)]
lst2=[i for i in range(11,20)]

out=list(map(lambda x,y:(x+y,y-x,x*y),lst1,lst2))
out

[(12, 10, 11),
 (14, 10, 24),
 (16, 10, 39),
 (18, 10, 56),
 (20, 10, 75),
 (22, 10, 96),
 (24, 10, 119),
 (26, 10, 144),
 (28, 10, 171)]

In [281]:
lst1=[i for i in range(1,11)]
lst2=[i for i in range(11,20)]
lst3=[i for i in range(20,30)]

sum1=sum(lst1+lst2+lst3)
sum2=list(map(lambda x,y,z:x+y+z,lst1,lst2,lst3))  #sum of lists using map and lambda function



'[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]'

In [233]:
lst1=[i for i in range(10,101,10)]
lst_index=[i for i in range(1,11)]

to_power=list(map(pow,lst1,lst_index))   #pow to raise to the power
to_power

[10,
 400,
 27000,
 2560000,
 312500000,
 46656000000,
 8235430000000,
 1677721600000000,
 387420489000000000,
 100000000000000000000]

In [268]:
lst_char=["d","a","b","B","c"]
k=set([s.upper() for s in lst_char])
l=[s.upper() for s in lst_char]
l.sort()
l
###for i in range(len(lst)):         also to update directly
###    lst[i] = lst[i].upper()


sorted_list=list(map(lambda x:str(x).upper(),lst_char))
sorted_list.sort()
set(sorted_list)

{'A', 'B', 'C', 'D'}

In [297]:
n=10

def fib(iteration):
    fibonacci=[0,1]
    for i in range(1,iteration):
            j=fibonacci[i]+fibonacci[i-1]
            fibonacci.append(j)
    return fibonacci

y=fib(10)

y=list(map(lambda x:x*x,y))
y

[0, 1, 1, 4, 9, 25, 64, 169, 441, 1156, 3025]

In [312]:
arr=[0,0,-1,-2,-3,4,5,6,7,8]

pos=list(filter(lambda x:x>0,arr))
neg=list(filter(lambda x:x<0,arr))
zero=list(filter(lambda x:x==0,arr))
len(arr)
p=len(pos)/len(arr)
n=len(neg)/len(arr)
z=len(zero)/len(arr)

print("ratio of postive, negative and zero is {} : {} : {}".format(p,n,z))

ratio of postive, negative and zero is 0.5 : 0.3 : 0.2


In [18]:
from urllib.request import urlopen as ureq
from bs4 import BeautifulSoup as soup
import pandas as pd

In [12]:
my_url="https://www.imdb.com/search/title/?sort=num_votes,desc&start=1&title_type=feature&year=1950,2012"
uclient=ureq(my_url)
page_html=uclient.read()
uclient.close()  #The close() method closes an open file. You should always close your files, in some cases, due to buffering, changes made to a file may not show until you close the file.

In [15]:
page_soup=soup(page_html) #html parser

In [17]:
filename=("Movies_IMDB.csv")
f=open(filename,"w")

header="Name, Year, Runtime \n"
f.write(header)


21

In [26]:
containers=page_soup.findAll("div", {"class": "lister-item mode-advanced"})
containers

[<div class="lister-item mode-advanced">
 <div class="lister-top-right">
 <div class="ribbonize" data-caller="filmosearch" data-tconst="tt0111161"></div>
 </div>
 <div class="lister-item-image float-left">
 <a href="/title/tt0111161/"> <img alt="The Shawshank Redemption" class="loadlate" data-tconst="tt0111161" height="98" loadlate="https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_UX67_CR0,0,67,98_AL_.jpg" src="https://m.media-amazon.com/images/S/sash/4FyxwxECzL-U1J8.png" width="67"/>
 </a> </div>
 <div class="lister-item-content">
 <h3 class="lister-item-header">
 <span class="lister-item-index unbold text-primary">1.</span>
 <a href="/title/tt0111161/">The Shawshank Redemption</a>
 <span class="lister-item-year text-muted unbold">(1994)</span>
 </h3>
 <p class="text-muted">
 <span class="certificate">A</span>
 <span class="ghost">|</span>
 <span class="runtime">142 min</span>
 <span class="ghost">|</span>
 <span 

In [57]:
filename=("Movies_IMDB.csv")
f=open(filename,"w")

header="Name, Year, Runtime \n"
f.write(header)

for i in containers:
    name=i.img["alt"]
    year_movie=i.findAll("span", {"class": "lister-item-year"})
    year=year_movie[0].text
    runtime=i.findAll("span", {"class": "runtime"})
    runtime=runtime[0].text
    print(name+ "," + year +"," + runtime +"\n")
    f.write(name+ "," + year +"," + runtime + "\n")

f.close()

The Shawshank Redemption,(1994),142 min

The Dark Knight,(2008),152 min

Inception,(2010),148 min

Fight Club,(1999),139 min

Forrest Gump,(1994),142 min

Pulp Fiction,(1994),154 min

The Matrix,(1999),136 min

The Lord of the Rings: The Fellowship of the Ring,(2001),178 min

The Godfather,(1972),175 min

The Lord of the Rings: The Return of the King,(2003),201 min

The Dark Knight Rises,(2012),164 min

The Lord of the Rings: The Two Towers,(2002),179 min

Se7en,(1995),127 min

Django Unchained,(2012),165 min

Gladiator,(2000),155 min

Batman Begins,(2005),140 min

Inglourious Basterds,(2009),153 min

The Silence of the Lambs,(1991),118 min

Saving Private Ryan,(1998),169 min

The Avengers,(2012),143 min

Star Wars,(1977),121 min

Schindler's List,(1993),195 min

The Prestige,(2006),130 min

Shutter Island,(2010),138 min

The Departed,(2006),151 min

Avatar,(2009),162 min

The Green Mile,(1999),189 min

The Empire Strikes Back,(1980),124 min

The Godfather Part II,(1974),202 min

Memen

In [68]:
for i in containers:
    name=i.img["alt"]
    year_movie=i.findAll("span", {"class": "lister-item-year"})
    year=year_movie[0].text
    runtime=i.findAll("span", {"class": "runtime"})
    runtime=runtime[0].text

    
year_movie[0].text

'(1980)'